sudo: required
services:
    - docker

before_install:
    - docker build -t sjdevel/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sjdevel/docker-react npm run test

language: generic 
